### PR TITLE
Beta to Prod... V. 2024.11.23.01

### LINKED ISSUE #4: Add V and X on UR's to ask for close as Solved or not identified
Change the options to "request to <br />solve" and "request to close as <br/>not identified" on UR's to ask for close as Solved or not identified

### PR DESCRIPTION
**Pull request by ordonezgs**
See changelog.

### CODE REVIEW

**Comment by ordonezgs** [comment]
This closes #4

**Comment by tunisiano187** [comment]
Hello, I've corrected the conflicts, can you test the script again ?

**Comment by ordonezgs** [comment]
> Hello, I've corrected the conflicts, can you test the script again ?

Testing results: Good. Ready to be merged.

**Comment by ordonezgs** [comment]
@tunisiano187 Would you disable SonarCloud Code Analysis or merge this PR manually?

**Comment by ordonezgs** [comment]
For some strange reason, after a quick fix related to [Nullish coalescing operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing) I'm able to merge this now.

**Pull request merged**
